name: MoneySigns
main: uk.co.drnaylor.moneysigns.MoneySigns
version: maven-version-number
depends: [Vault]
commands:
  msid:
    description: Sets, gets and removes stored identifiers
    usage: /msid <get|set|remove> [identifier] [timeout]
    permission: moneysigns.command.msid
    permission-message: You don't have permission to perform that command!
  msclear:
    description: Clears a players' cooldown
    usage: /msclear [player] [id]
    permission: moneysigns.command.msclear
    permission-message: You don't have permission to perform that command!
  signprizes:
    aliases: [sp]
    description: Defines, modifies, and removes prize identifiers.
    usage: /signprizes <define|modify|info|remove|defineset|modifyset|definesetmoney|setinfo|setremove> <id> [...]
    permission: signprizes.command.sp
    permission-message: You don't have permission to perform that command!
  spdefine:
    aliases: [signprizesdefine,spdef,signprizesdef]
    description: Defines prize identifiers and sets.
    usage: /spdefine <ID|set> <IDName|setName> <parameters>
    permission: signprizes.commands.spdefine
    permission-message: You don't have permission to perform that command!
  spmodify:
    aliases: [signprizesmodify,spmod,signprizesmod]
    description: Modifies prize identifiers and sets.
    usage: /spmodify <ID|set> <IDName|setName> <parameters>
    permission: signprizes.commands.spmodify
    permission-message: You don't have permission to perform that command!
